import { lusitana } from "@/assets/font";
import type { Metadata } from "next";

import "@/styles/globals.css";
import Provider from "./Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lusitana.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
